[project]
name = "nscene"
version = "0.1.0"
description = "PySide6 Nuke scene open and save browser"
readme = "README.md"
authors = [
    { name = "Rob", email = "robertvigorito@gmail.com" }
]
requires-python = ">=3.12"
dependencies = ["PySide6>=6.8.1", "pymongo>=4.15.3"]

[project.scripts]
nscene = "nscene:main"

[tool.uv]
package = true

[dependency-groups]
dev = [
    "mypy>=1.15",
    "pytest>=8.3",
    "ruff>=0.9",
]

[build-system]
requires = ["uv_build>=0.9.11,<0.10.0"]
build-backend = "uv_build"
